### PR TITLE
Deprecate tsd in favour of typings.

### PR DESCRIPTION
**Pull request by SethDavenport**
Still need to hunt down a few typing-related errors:

```
ERROR in ./src/reducers/index.tsx
(2,30): error TS2307: Cannot find module 'redux-simple-router'.

ERROR in ./src/store/configureStore.tsx
(5,43): error TS2307: Cannot find module 'redux-simple-router'.

ERROR in ./src/store/configureStore.tsx
(40,14): error TS2339: Property 'hot' does not exist on type 'NodeModule'.

ERROR in ./src/store/configureStore.tsx
(41,12): error TS2339: Property 'hot' does not exist on type 'NodeModule'.

ERROR in /Users/sdavenpo/code/rangle/typescript-react-redux-starter/typings/main/ambient/webpack-env/webpack-env.d.ts
(185,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'RequireFunction'.

ERROR in /Users/sdavenpo/code/rangle/typescript-react-redux-starter/typings/main/ambient/webpack-env/webpack-env.d.ts
(234,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NodeModule', but here has type 'Module'.
```

### CODE REVIEW

**Comment by SethDavenport** [comment]
@bertrandk : I can't seem to find typings for `react-simple-router` where did they originally come from?

**Comment by bertrandk** [comment]
I honestly can't recall. This looks better anyways: https://github.com/rackt/react-router-redux/issues/151

**Comment by bertrandk** [comment]
I actually meant to paste this issue: https://github.com/rackt/react-router-redux/pull/204

**Comment by SethDavenport** [comment]
Thanks Betrand - DT has typings for react-router-redux under the new name.  This also means that this PR does part of https://github.com/rangle/rangle-starter/issues/6

**Pull request merged**
