### PR TITLE
Small fix for a broken import path

### PR DESCRIPTION
**Pull request by cramhead**
ts-react: The index file was not included in the path. 
sorry, I'm not too sure how to make a label.

### CODE REVIEW

**Comment by cramhead** [comment]
Actually, I found a number other places where the same problem exists. I think it best to reject this pull request and fix all entries at once.

**Comment by SethDavenport** [comment]
Hi @cramhead - thanks for taking the time to look into it.  However, I don't think this is bug. Node allows you to import a folder that contains an `index.js` file. So these are not broken paths, just shorthand.

When I build the app, it runs fine for me.  If you are getting errors, can you paste them here?

**Comment by cramhead** [comment]
Thanks for the insight Seth. I guess the error is either with my configuration or  in the typescript service that Webstorm depends upon. Webstorm flags the import as an error when I open each file that depends on the folder import.

**Comment by SethDavenport** [comment]
Asked around and it seems that typescript prior to 1.8 didn't support this style of import, but it does now.  I wonder if webstorm is using is different version of typescript to show in-editor errors?

There may be a way to tell it to use the typescript version from node_modules instead; I had to do something similar to vscode for 1.8's functional stateless component support: https://github.com/rangle/typescript-react-redux-starter/blob/master/.vscode/settings.json

I don't use webstorm so I'm not sure.

**Pull request closed without merging**
