### PR TITLE
WIP Move to basscss-radium

### PR DESCRIPTION
**Pull request by SethDavenport**
Get rid of className stuff; it's all inline styles now.

### CODE REVIEW

**Comment by SethDavenport** [comment]
@bertrandk : is this more what you had in mind for CSS?

**Comment by SethDavenport** [comment]
If so, let me know and I'll patch it over to the babel react starter.

**Comment by SethDavenport** [comment]
@bertrandk @varun @mattmischuk thoughts?

**Comment by mattmischuk** [comment]
I have very limited knowledge of radium basscss so take this with a grain of salt. However in my last radium project this really worked well for us.

We wen't nuts with making small components and instead of making objects called `container` or `button` we would break them into new components and only have a `base:` style and then the various states on that component. That's it.

Thoughts?

See example from Infosec:

```js
const styles = {
  base: {
    background: buttonColor.base,
    border: `${ border.thinStroke } ${ buttonColor.fullDarkness }`,
    borderRadius: border.baseRadius,
    boxShadow: form.outlineBoxShadowEmpty,
    color: buttonColor.text,
    display: 'block',
    marginTop: basscssDefaults.space1,
    padding: `${ basscssDefaults.space1 } ${ basscssDefaults.space2 }`,
    textTransform: 'uppercase',
    fontSize: typography.smallFontSize,
    width: '100%',
    transitionProperty: 'background, transform, boxShadow',
    transitionDuration: transition.baseDuration,
    transitionTimingFunction: transition.easeInOutSine,

    ':hover': {
      background: buttonColor.dark,
    },

    ':active': {
      transform: 'scale(0.99)',
    },

    ':focus': {
      outline: 'none',
      boxShadow: form.outlineBoxShadow,
    },
  },
};
```

**Comment by mattmischuk** [comment]
Here's a snippet from radiums docs:
```js
var styles = {
  base: {
    background: 'blue',
    border: 0,
    borderRadius: 4,
    color: 'white',
    padding: '1.5em',

    ':hover': {
      backgroundColor: 'red'
    },

    ':focus': {
      backgroundColor: 'green'
    },

    ':active': {
      backgroundColor: 'yellow'
    },
  },

  block: {
    display: 'block',

    ':hover': {
      boxShadow: '0 3px 0 rgba(0,0,0,0.2)'
    }
  },
};
```

**Comment by SethDavenport** [comment]
Verbal discussion with @bertrandk today - I'm on the right track but I need to ingrate Radium properly.

**Comment by SethDavenport** [comment]
Closing for now.  Will come back to it later if it's still the correct approach.

**Pull request closed without merging**
